Feat operateur by hab
pebble-solutions/App-QSE-controle pull request #118
Opened 2023-06-22 13:01 UTC by marilehoux

je veux bien que tu regardes. j'ai toujours le saut dans la page operateur

2023-06-22 13:09 UTC, Guillaume35 commented on src/App.vue
> +			else if (['Habilitation',
Au vu du nombre de nom de routes à cet endroit, désormais, il est préférable de déclarer une constante en entête de fichier avec l'ensemble des nom de routes acceptées.

```JavaScript
const ROUTES_HABILITATION = [...liste des noms de routes]; 
```

Puis au niveau de la condition, il suffira d'utiliser la constante pour tester la route active :

```JavaScript
if (ROUTES_HABILITATION.includes(this.$route.name))
```

2023-06-22 13:09 UTC, Guillaume35 commented on src/App.vue
> +				else if (['Operateur',
Idem

2023-06-22 13:11 UTC, Guillaume35 commented on src/components/ConsultationCollecteResume.vue
> +                 .then((data) => {console.log(data,'pdf')})
Il ne se passe rien sur cette action.
Dans l'idée, il faut ouvrir l'URL reçu pour afficher le PDF.

2023-06-22 13:17 UTC, Guillaume35 commented on src/views/ControlHistory.vue
> +		changeFormatDateLit(el) {
Identation à revoir

2023-06-22 14:43 UTC, Guillaume35 requested changes
Ajouter le bouton PDF fonctionnel plz

2023-06-22 21:41 UTC, Guillaume35 approved these changes

2023-06-22 21:43 UTC, Guillaume35 commented
Je vais devoir réaliser un merge manuel sur cette pull request

2023-06-22 21:45 UTC, marilehoux commented
Pourquoi? J’ai merdé un truc?

> Le 22 juin 2023 à 23:43, Guillaume Modard ***@***.***> a écrit :
> 
> 
> Je vais devoir réaliser un merge manuel sur cette pull request
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/pebble-solutions/App-QSE-controle/pull/118#issuecomment-1603353879>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVB4DWRHKHIANBI4XVML4CLXMS4BVANCNFSM6AAAAAAZQFUWYU>.
> You are receiving this because you authored the thread.
>

2023-06-23 07:49 UTC, Guillaume35 requested changes
Gros débug à faire. La création de nouvelle collecte ne fonctionne plus correctement.

2023-06-26 08:35 UTC, Guillaume35 approved these changes

2023-06-26 08:35 UTC, Guillaume35 commented on src/views/HabilitationAgent.vue
> +                    <div>
Je ferme les yeux sur l'indentation :-p

2023-06-26 08:36 UTC, merged