Ajout des listes filtrées dans la consultation
pebble-solutions/App-QSE-controle pull request #228
Opened 2023-08-14 21:01 UTC by TigrouForMatic

UI

2023-08-17 14:39 UTC, Guillaume35 requested changes

2023-08-17 14:39 UTC, Guillaume35 commented on src/components/SearchControl.vue
> +                kns: knsFilter
`kns` devient `result_var` il me semble

2023-08-17 14:39 UTC, Guillaume35 commented on src/config.json
> +            "authServer": "172.17.0.4:3333",
oupsi, on a encore un .4 ici ;-)

2023-08-17 14:39 UTC, Guillaume35 commented on src/js/search-consultation.js
> +        }
Par rapport à ce qui est indiqué ici, le teste du stats_dd et stats_df n'est pas utile au niveau du backoffice car il est bien contrôlé d'ici.

2023-08-17 14:39 UTC, Guillaume35 commented on src/js/search-consultation.js
> + * - {array}  kns           Liste des valeur SAMI des controles filtrés
remplacer kns par result_var

2023-08-17 14:39 UTC, Guillaume35 commented on src/js/search-consultation.js
> +            query.result_var = searchParams.kns;
supprimer cette ligne.

2023-08-17 14:39 UTC, Guillaume35 commented on src/js/search-consultation.js
> +            result_var: null
remplacer `null` par `searchParams.result_var ?? null`

2023-08-21 18:00 UTC, deathtroll22 commented
j'ai fini les task sur la 185, essentielement de l'affichage, mais j'ai du faire sauter un attribut margin auto sur le composant user image dans PEBBLE UI. je créée donc une pull request supplementaire pour pebble ui

2023-09-01 10:50 UTC, Guillaume35 approved these changes
Attention : des modifications qui ne rentre pas dans le champ de cette branche ont été ajoutées dessus après la demande de pull request par @deathtroll22 . Il est important que chaque nouveaux ajouts de fonction ou d'amélioration face l'objet d'une branche distincte

2023-09-01 11:07 UTC, merged